Repository shannonmoranetz/trapper-keeper-ui, pull requests merged in 2019-02, with the labels that each got.

#13 Fix errors Create Note, Use proper control form
  src/containers/CreateNote/CreateNote.js
  src/containers/NoteArea/NoteArea.js
  src/containers/NoteArea/NoteCard/NoteCard.js
Labels: Functionality, bug

#21 Implement post thunk, layout framework for put and delete thunks
  src/containers/App/App.js
  src/containers/CreateNote/CreateNote.js
  src/thunks/getNotes.js
  src/thunks/index.js
  src/utils/api.js
Labels: in progress

#26 Update items on form
  src/actions/index.js
  src/containers/App/App.js
  src/containers/CreateNote/CreateNote.js
  src/containers/NoteArea/NoteCard/NoteCard.js
  src/reducers/currentNoteReducer.js
  src/reducers/index.js
  src/reducers/notesReducer.js
  src/reducers/showPopUpReducer.js
  src/thunks/index.js
  src/thunks/index.test.js
  src/utils/api.js
Labels: Functionality, P1, User Story, enhancement
